version: '3'

services:
   frontend:
     build: ./tursu
     command : npm start
     volumes:
       - ./tursu:/frontend
     ports:
       - 3000

     #nginx:
    # image: nginx:latest
    # ports:
    #   - 80:8080
    # volumes:
    #   - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    #   - build_folder:/var/www/frontend
    # depends_on:
    #   - backend
    #   - frontend

