version: '3'

services:
  frontend:
    build: ./tursu
    command : npm start
    volumes:
      - ./tursu:/frontend
    ports:
      - 3000

  nginx:
    build: ./nginx
    ports:
      - 30:30
    depends_on:
      - frontend
    #nginx:
    # image: nginx:latest
    # ports:
    #   - 80:8080
    # volumes:
    #   - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    #   - build_folder:/var/www/frontend
    # depends_on:
    #   - backend
    #   - frontend
