version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data/
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=tursu123
      - POSTGRES_DB=tursu_db
volumes:
  db:
  # frontend:
  #   build:
  #     context: ./frontend
  #     args:
  #       API_URL: *
  #   volumes:
  #     - build_folder:/frontend/build
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:8080
  #   volumes:
  #     - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
  #     - build_folder:/var/www/frontend
  #   depends_on:
  #     - backend
  #     - frontend
# volumes:
#   build_folder: